# Generated by Django 3.1.7 on 2021-03-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xs', 'xsmall'), ('sm', 'small'), ('md', 'medium'), ('lg', 'large'), ('xl', 'xlarge')], default='md', max_length=31)),
                ('name', models.CharField(max_length=127)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=0, help_text='walk distance (in meters)')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks', to='myapp.dog')),
            ],
        ),
    ]
